language: rust
rust:
  - nightly
env:
  - FEATURE_ARGS=
  - FEATURE_ARGS="--features no-docopt-macros --no-default-features"
script:
  - cargo build --verbose $FEATURE_ARGS
  - cargo test --verbose $FEATURE_ARGS
  - if [ "$FEATURE_ARGS" = "" ]; then ./sample-run.sh; fi